### ISSUE TITLE
Prosposed change to metOcean KB.

### ISSUE THREAD

**Issue by gm-s** [metarelate/metOcean#40]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
https://beta.metarelate.net/metOcean/controlpanel/?branch=8ac2091008da3f65a3ec9d518c89d11921c98542%2F

**Comment by marqh** [comment]
Hello
I am sorry, but I broke your branchgraph due to a bug, which has deleted its contents.
please may you repeat your upload?
thank you
mark

**Comment by gm-s** [comment]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@gm-s
@marqh
https://beta.metarelate.net/metOcean/controlpanel/?branch=8ac2091008da3f65a3ec9d518c89d11921c98542%2F

**Comment by marqh** [comment]
merged
thank you
