### ISSUE TITLE
CLASSIC section 0 fixes v2

### ISSUE THREAD

**Issue by nhsavage** [metarelate/metOcean#42]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@nhsavage
@marqh
https://beta.metarelate.net/metOcean/controlpanel/?branch=e74ceeafcd63b1eea8ab28d6232956ec86c602da%2F

**Comment by marqh** [comment]
These all look good

merged and pushed to Iris for adoption
https://github.com/SciTools/iris/pull/1557

**Comment by marqh** [comment]
Iris updated successfully
