### ISSUE TITLE
Proposed Stash-CF mapping for Visibility at Screen Level: visibility_in_air.

### ISSUE THREAD

**Issue by gm-s** [metarelate/metOcean#44]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@gm-s
https://www.metarelate.net/metOcean/controlpanel/?branch=a804eb681f1170d909c8a13c7f2771e726bab8e8%2F

**Comment by marqh** [comment]
I would prefer to capture the at 1.5m information as well, but there are further changes needed for this.  For now, we'll adopt this, then upgrade it to include the height constraint.

there are other items which this is required for #45

**Comment by marqh** [comment]
merged and pushed to Iris:
https://github.com/SciTools/iris/pull/1562
