### ISSUE TITLE
139 STASH code -> CF name (63 new)

### ISSUE THREAD

**Issue by ehogan** [metarelate/metOcean#54]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@marqh
@ehogan
@jkettleb
https://www.metarelate.net/metOcean/controlpanel/?branch=212f760b87efee54a2f4d946e079fb050ffd700c%2F

**Comment by ehogan** [comment]
@marqh apologies, I just noticed that you requested I submit the new translations seperately from those that are consistence with metarelate. I can still do that if you'd prefer? Please let me know :)

**Comment by marqh** [comment]
no, that's fine, all of these entries are new, or supporting existing entries, so we can handle all of them together

**Comment by ehogan** [comment]
@marqh I took out the unrecognised STASH codes (there were 8; there are only 55 new translation now), so everything should be ready for you :)

**Comment by marqh** [comment]
this is all validated and merged

many thanks @ehogan

**Comment by jkettleb** [comment]
Do we understand why we have unrecognised stash codes?  My guess is they are stash codes that came in through a user stash master file - but I'm not sure.

**Comment by marqh** [comment]
hello @jkettleb 
> Do we understand why we have unrecognised stash codes? My guess is they are stash codes that came in through a user stash master file - but I'm not sure.

please could you comment on the related issue:
#60 
so that we can continue this conversation.  I would like to close this issue as the changes (excluding the unrecognised STASH codes) are merged into metOcean and Iris now

thank you
mark

**Comment by jkettleb** [comment]
have added a comment to #60.  Do you need anything else before you can close this ticket?  Jamie

**Comment by marqh** [comment]
> Do you need anything else before you can close this ticket? Jamie

That's grand, no more needed for this one

thank you
