### ISSUE TITLE
Cloud/radiation/aerosol stash->cf name update

### ISSUE THREAD

**Issue by malcolmbrooks** [metarelate/metOcean#59]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@malcolmbrooks
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=2dc611363670c270cfeed6bb0d6e35ba9caf2c4e%2F

**Comment by marqh** [comment]
this is all validated and merged
many thanks malcolm

**Comment by marqh** [comment]
merged onto Iris
