### ISSUE TITLE
GRIB2 precipitation amount

### ISSUE THREAD

**Issue by marqh** [metarelate/metOcean#61]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=11f224c43815467cbdc1fbd544359b041cd4dae0%2F

**Comment by marqh** [comment]
@marqh ???

**Comment by marqh** [comment]
merged

**Comment by rhattersley** [comment]
> https://www.metarelate.net/metOcean/controlpanel/?branch=11f224c43815467cbdc1fbd544359b041cd4dae0%2F

Just trying to do due diligence before merging SciTools/iris#1929, but your link doesn't seem to show anything useful ... perhaps because the content has already been merged (in 4ed3b57)? The contents of that commit are not exactly easy to interpret either. Is there a human-readable way to see what was changed?

**Comment by marqh** [comment]
Hi @rhattersley 

the www.metarelate link becomes null when the changes are merged

the most human readable approach is to take the URI from the mapping added
https://github.com/metarelate/metOcean/commit/4ed3b57ab5bebf17181e0309c1edb72678784d25#diff-bfe01bf3f6bd7cf9decabe5a42aee5cbR887

and ping it
http://www.metarelate.net/metOcean/mapping/11fa8f60492d353b9925b642506825ad286f1f7b

this is what the link in the ticket did, prior to the content merge

hope this helps
mark

**Comment by rhattersley** [comment]
> the most human readable approach is to take the URI from the mapping added ... and ping it

Is there a simple way to automate that? e.g. Something equivalent to https://www.metarelate.net/metOcean/controlpanel/?branch=11f224c43815467cbdc1fbd544359b041cd4dae0%2F but which still functions after the content has been merged.

**Comment by marqh** [comment]
hmmm, that is somewhat harder

the branch is emptied at the point of merge, content in the adopted mappings has no knowledge of the branch it came from, so there isn't a simple way that I can see to maintain the link back to the proposed changes

i'll have to think about that one some more and see if there's a neat way in
