### ISSUE TITLE
Incorrect units for tendency_of_upward_air_velocity_due_to_advection

### ISSUE THREAD

**Issue by rhattersley** [metarelate/metOcean#63]
The units for `tendency_of_upward_air_velocity_due_to_advection` are incorrect. This repo says [m s-1](https://github.com/metarelate/metOcean/blob/master/staticData/metarelate.net/concepts.ttl#L8514) but the [CF standard name table](http://cfconventions.org/Data/cf-standard-names/29/build/cf-standard-name-table.html) says "m s-2". The latter makes more sense as it's a tendency (aka. rate of change) of a velocity.

**Comment by marqh** [comment]
fixed by #65
