### ISSUE TITLE
Added mappings

### ISSUE THREAD

**Issue by lbdreyer** [metarelate/metOcean#66]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@lbdreyer
https://www.metarelate.net/metOcean/controlpanel/?branch=076321d5f4c4e8e8bfee79ac3a37d5233e684b24%2F

**Comment by marqh** [comment]
9221 -> wet_bulb_freezing_level_height (m)
 
This is an “altitude” defined with respect to sea level. It is not a “height” defined wrt the local surface.

**Comment by rhattersley** [comment]
That suggests the name should be "web_bulb_freezing_level_height_above_sea_level".

**Comment by marqh** [comment]
>>freezing_level_altitude
> Altitude is the (geometric) height above the geoid, which is the reference geopotential surface. The geoid is similar to mean sea level.
http://vocab.nerc.ac.uk/standard_name/freezing_level_altitude/

I think this is suggesting that in CF terms altitude is used to describe height above mean sea level

there are very few standard names with heigh_above_sea_level and these appear to refer to local sea level

**Comment by rhattersley** [comment]
Hmmm... possibly this discussion would be better taking place on the CF mailing list, but...

"similar" is not the same as "the same as".

In particular, elsewhere in the standard name table the help text explicitly describes the difference between geoid and mean sea level and that they would be the same if the sea were at rest.

**Comment by marqh** [comment]
the quantity is defined with respect to the model's interpretation of mean sea level, which is interpreted in CF terms as the geoid, according to the code owner of this stash section.

'altitude' is deemed appropriate for use in this name and for this mapping

**Comment by rhattersley** [comment]
Since the model is using the geoid for mean sea level then "altitude" is fine. Which leaves us with: `web_bulb_freezing_level_altitude` :+1:

**Comment by marqh** [comment]
@lbdreyer please may you update
https://www.metarelate.net/metOcean/controlpanel/?branch=076321d5f4c4e8e8bfee79ac3a37d5233e684b24%2F
with this alternative name

thank you

**Comment by lbdreyer** [comment]
I think I have now updated the branch with the new name.

**Comment by marqh** [comment]
this looks grand
merged
