### ISSUE TITLE
STASH code to CF name: relative humidity

### ISSUE THREAD

**Issue by rcomer** [metarelate/metOcean#67]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@rcomer
https://www.metarelate.net/metOcean/controlpanel/?branch=917c14a8e4c94c58423cba9614ce7c8f633cabac%2F

**Comment by marqh** [comment]
apologies for the tardy response on this; I was under the impression that this was a work in progress.

Is this a mistake, is this ticket complete from your point of view @rcomer ?

**Comment by marqh** [comment]
https://reference.metoffice.gov.uk/um/stash/m01s30i404
describes 
Total Column Wet Mass

http://vocab.nerc.ac.uk/standard_name/atmosphere_mass_per_unit_area/
seems a less apt description of this quantity than
http://vocab.nerc.ac.uk/standard_name/atmosphere_mass_content_of_water/

They unit of measure seems constant across both.

@rcomer please may you provide a little more information on why this change is required and your confidence in the name change

thank you
mark

**Comment by rcomer** [comment]
[Total column wet mass](https://reference.metoffice.gov.uk/um/stash/m01s30i404) gives the total mass of the column, including water.  We also have [Total column dry mass](https://reference.metoffice.gov.uk/um/stash/m01s30i403), which is the total mass of the column not including water.  So to get the column water mass, we do "wet mass" minus "dry mass".

I have to admit that I'm not very familiar with the cf standard names, but to me "atmosphere_mass_content_of_water" suggests the difference between the two stash diagnostics, rather than just "wet mass".

**Comment by marqh** [comment]
Hi @rcomer 

that makes sense, we will take your view on this and adopt it

I have merged the changes so we can close this ticket
thank you for the contribution
mark
