### ISSUE TITLE
Add m01s03i227 to the STASHCODE_IMPLIED_HEIGHTS dictionary

### ISSUE THREAD

**Issue by ehogan** [metarelate/metOcean#70]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@ehogan
https://www.metarelate.net/metOcean/controlpanel/?branch=289bc7643ba6385bf0ff51f28380d05776248f50%2F

**Comment by marqh** [comment]
this makes eminent sense to me, the STASH reference clearly states it is at 10m above the surface
http://reference.metoffice.gov.uk/um/stash/m01s03i227

This is good to go

**Comment by marqh** [comment]
https://github.com/SciTools/iris/pull/1929
