### ISSUE TITLE
STASH to GRIB2 translation from ff2grib users

### ISSUE THREAD

**Issue by scwhitehouse** [metarelate/metOcean#73]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@scwhitehouse
@ehogan
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=8387fb07ba470fd43d8aa9211ce5333add78bcd6%2F

https://www.metarelate.net/metOcean/controlpanel/?branch=8387fb07ba470fd43d8aa9211ce5333add78bcd6%2F

**Comment by marqh** [comment]
following off line discussions with @scwhitehouse, these are merged onto master.

**Comment by marqh** [comment]
this is based on long standing practice for FF to GRIB conversion requirements
