### ISSUE TITLE
STASH code to CF name translations: corrections and additions for GLOMAP-mode

### ISSUE THREAD

**Issue by jhemmings** [metarelate/metOcean#74]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@jhemmings
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=c51aae57a9b9cc192695ef18aa2e057d562d844e%2F

**Comment by marqh** [comment]
merged and adopted with thanks

pushed to Iris in
https://github.com/SciTools/iris/pull/3011
