### ISSUE TITLE
expired certificate

### ISSUE THREAD

**Issue by tv3141** [metarelate/metOcean#80]
www.metarelate.net uses an invalid security certificate. The certificate expired on 02/12/17 23:59. The current time is 08/03/17 15:38. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by marqh** [comment]
hello @tv3141 

thank you for the notification, this was fixed some time ago, so I'm closing this ticket, I hope that is reasaonable

marqh
