### ISSUE TITLE
STASH code to CF name translations: corrections for GLOMAP-mode 

### ISSUE THREAD

**Issue by jhemmings** [metarelate/metOcean#81]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@jhemmings
https://www.metarelate.net/metOcean/controlpanel/?branch=f8d4c075df5f1ccee66eed8fffb34c6104718d5b%2F

**Comment by marqh** [comment]
merged and adopted with thanks

pushed to Iris in
https://github.com/SciTools/iris/pull/3011
