### ISSUE TITLE
 STASH code to CF name translations: photolysis and nmvoc additions

### ISSUE THREAD

**Issue by jhemmings** [metarelate/metOcean#82]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@jhemmings
https://www.metarelate.net/metOcean/controlpanel/?branch=ffc0a84ed952530f0a59ff04c7428fc9214473e1%2F

Copy of text in the uploaded file:

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s50i228|photolysis_rate_of_ozone_to_1D_oxygen_atom|s-1|n|
|m01s50i229|photolysis_rate_of_nitrogen_dioxide|s-1|n|
|m01s50i230|mass_concentration_of_nmvoc_expressed_as_carbon_in_air|ug m-3|n|

**Comment by marqh** [comment]
merged and adopted with thanks

pushed to Iris in
https://github.com/SciTools/iris/pull/3011
