### ISSUE TITLE
STASH Code to CF name translations: Inconsistent units and names

### ISSUE THREAD

**Issue by pdearnshaw** [metarelate/metOcean#83]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pdearnshaw
@scwhitehouse
@ehogan
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=f5ad340edfda2d2cca601e7e4699e94ab7102de0%2F

**Comment by pdearnshaw** [comment]
Copy of text in the uploaded file:

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s00i106|mass_fraction_of_hydrogen_peroxide_in_air|kg kg-1|y|
|m01s00i124|mass_fraction_of_hydrogen_peroxide_in_air|kg kg-1|y|
|m01s00i125|mass_fraction_of_ozone_in_air|kg kg-1|y|
|m01s00i418|volume_fraction_of_clay_in_soil|m3 m-3|y|
|m01s00i419|volume_fraction_of_silt_in_soil|m3 m-3|y|
|m01s00i420|volume_fraction_of_sand_in_soil|m3 m-3|y|
|m01s01i238|tropopause_upwelling_shortwave_flux|W m-2|y|
|m01s02i207|surface_downwelling_longwave_flux_in_air|W m-2|y|
|m01s02i208|surface_downwelling_longwave_flux_in_air_assuming_clear_sky|W m-2|y|
|m01s02i351|equivalent_reflectivity_factor|dBZ|y|
|m01s03i004|air_temperature|K|y|
|m01s03i202|downward_heat_flux_in_soil|W m-2|y|
|m01s03i219|atmosphere_downward_eastward_stress|Pa|y|
|m01s03i220|atmosphere_downward_northward_stress|Pa|y|
|m01s03i245|relative_humidity|1|y|
|m01s03i263|plant_respiration_carbon_flux|kg m-2 s-1|y|
|m01s03i293|soil_respiration_carbon_flux|kg m-2 s-1|y|
|m01s04i203|stratiform_rainfall_flux|kg m-2 s-1|y|
|m01s04i204|stratiform_snowfall_flux|kg m-2 s-1|y|
|m01s05i205|convective_rainfall_flux|kg m-2 s-1|y|
|m01s05i212|convective_cloud_area_fraction_in_atmosphere_layer|1|y|
|m01s08i208|soil_moisture_content|kg m-2|y|
|m01s08i209|canopy_water_amount|kg m-2|y|
|m01s08i229|mass_fraction_of_unfrozen_water_in_soil_moisture|1|y|
|m01s08i230|mass_fraction_of_frozen_water_in_soil_moisture|1|y|
|m01s08i233|canopy_throughfall_flux|kg m-2 s-1|y|
|m01s15i219|square_of_air_temperature|K2|y|
|m01s15i220|square_of_eastward_wind|m2 s-2|y|
|m01s15i221|square_of_northward_wind|m2 s-2|y|
|m01s15i223|product_of_omega_and_air_temperature|K Pa s-1|y|
|m01s15i224|product_of_eastward_wind_and_omega|Pa m s-2|y|
|m01s15i225|product_of_northward_wind_and_omega|Pa m s-2|y|
|m01s15i226|specific_humidity|kg kg-1|y|
|m01s15i227|product_of_eastward_wind_and_specific_humidity|m s-1|y|
|m01s15i228|product_of_northward_wind_and_specific_humidity|m s-1|y|
|m01s15i235|product_of_omega_and_specific_humidity|Pa s-1|y|
|m01s15i238|geopotential_height|m|y|
|m01s15i239|product_of_eastward_wind_and_geopotential_height|m2 s-1|y|
|m01s15i240|product_of_northward_wind_and_geopotential_height|m2 s-1|y|
|m01s16i204|relative_humidity|1|y|
|m01s16i256|relative_humidity|1|y|
|m01s30i113|relative_humidity|1|y|
|m01s30i218|product_of_eastward_wind_and_omega|Pa m s-2|y|
|m01s30i228|product_of_northward_wind_and_omega|Pa m s-2|y|
|m01s33i150|age_of_stratospheric_air|s|y|

**Comment by scwhitehouse** [comment]
Possibly a silly question, but some of these netCDF names contain "northward" and "eastward" - when the data is on a rotated pole, "north" isn't really north. Does the standard allow the use of "northward" and "eastward" in these cases?

**Comment by pdearnshaw** [comment]
Not a silly question, but I do not know the answer. There is the concept of x_wind and y_wind in the standard but it is not used for any of the more contrived names. A search of the CF standard name table shows these are only used for the absolute field. As a point of principle there should probably be variations with x_wind and y_wind but that should be a topic for the CF standards people (and possibly their reluctance to allow templated names).

**Comment by pdearnshaw** [comment]
This is also more likely a function of the fact that most of the names are generated from needs in the global modelling community, or where the fields have been unrotated.

**Comment by marqh** [comment]
hello @pdearnshaw @scwhitehouse 

the rules within CF state that 'eastward_' should always mean east

`x_`
means in the `i` direction of the horizontal grid (more or less).  This is allowed to be east, nearly east, or not at all east.

preference within downstream applications is to use 
`x_{thing}`  over `eastward_{thing}`

in many (most) cases these names are not in the standard names list, so metarelate and other applications will use the long_name field for these values

@pdearnshaw 
if you would be happy to update these inputs:
  * `eastward_` => `x_`
  * `northward_` => `y_`

then I think these would be good to adopt

**Comment by pdearnshaw** [comment]
Have updated the branch with the following:

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s00i106|mass_fraction_of_hydrogen_peroxide_in_air|kg kg-1|y|
|m01s00i124|mass_fraction_of_hydrogen_peroxide_in_air|kg kg-1|y|
|m01s00i125|mass_fraction_of_ozone_in_air|kg kg-1|y|
|m01s00i418|volume_fraction_of_clay_in_soil|m3 m-3|y|
|m01s00i419|volume_fraction_of_silt_in_soil|m3 m-3|y|
|m01s00i420|volume_fraction_of_sand_in_soil|m3 m-3|y|
|m01s01i238|tropopause_upwelling_shortwave_flux|W m-2|y|
|m01s02i207|surface_downwelling_longwave_flux_in_air|W m-2|y|
|m01s02i208|surface_downwelling_longwave_flux_in_air_assuming_clear_sky|W m-2|y|
|m01s02i351|equivalent_reflectivity_factor|dBZ|y|
|m01s03i004|air_temperature|K|y|
|m01s03i202|downward_heat_flux_in_soil|W m-2|y|
|m01s03i219|atmosphere_downward_eastward_stress|Pa|y|
|m01s03i220|atmosphere_downward_northward_stress|Pa|y|
|m01s03i245|relative_humidity|1|y|
|m01s03i263|plant_respiration_carbon_flux|kg m-2 s-1|y|
|m01s03i293|soil_respiration_carbon_flux|kg m-2 s-1|y|
|m01s04i203|stratiform_rainfall_flux|kg m-2 s-1|y|
|m01s04i204|stratiform_snowfall_flux|kg m-2 s-1|y|
|m01s05i205|convective_rainfall_flux|kg m-2 s-1|y|
|m01s05i212|convective_cloud_area_fraction_in_atmosphere_layer|1|y|
|m01s08i208|soil_moisture_content|kg m-2|y|
|m01s08i209|canopy_water_amount|kg m-2|y|
|m01s08i229|mass_fraction_of_unfrozen_water_in_soil_moisture|1|y|
|m01s08i230|mass_fraction_of_frozen_water_in_soil_moisture|1|y|
|m01s08i233|canopy_throughfall_flux|kg m-2 s-1|y|
|m01s15i219|square_of_air_temperature|K2|y|
|m01s15i220|square_of_x_wind|m2 s-2|y|
|m01s15i221|square_of_y_wind|m2 s-2|y|
|m01s15i223|product_of_omega_and_air_temperature|K Pa s-1|y|
|m01s15i224|product_of_x_wind_and_omega|Pa m s-2|y|
|m01s15i225|product_of_y_wind_and_omega|Pa m s-2|y|
|m01s15i226|specific_humidity|kg kg-1|y|
|m01s15i227|product_of_x_wind_and_specific_humidity|m s-1|y|
|m01s15i228|product_of_y_wind_and_specific_humidity|m s-1|y|
|m01s15i235|product_of_omega_and_specific_humidity|Pa s-1|y|
|m01s15i238|geopotential_height|m|y|
|m01s15i239|product_of_x_wind_and_geopotential_height|m2 s-1|y|
|m01s15i240|product_of_y_wind_and_geopotential_height|m2 s-1|y|
|m01s16i204|relative_humidity|1|y|
|m01s16i256|relative_humidity|1|y|
|m01s30i113|relative_humidity|1|y|
|m01s30i218|product_of_x_wind_and_omega|Pa m s-2|y|
|m01s30i228|product_of_y_wind_and_omega|Pa m s-2|y|
|m01s33i150|age_of_stratospheric_air|s|y|

**Comment by marqh** [comment]
merged, with thanks
