### ISSUE TITLE
STASH Code to CF name translations: Modifying increment diagnostic standard names

### ISSUE THREAD

**Issue by pdearnshaw** [metarelate/metOcean#84]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pdearnshaw
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=e495ddb6f15314fed40b632f782b8f74f3e74581%2F

**Comment by pdearnshaw** [comment]
To put context on these changes, the "tendency_of_<prognostic>[_due_to_<process>]" standard names are defined to be rates of change of the prognostic with respect to time, i.e. they are all dX/Dt and have units "[X] s-1". For example, tendency_of_air_temperature has units "K s-1". The increment diagnostics that are output from the UM are all dX's, i.e. they are absolute differences and not rates. There are precedents in the CF standard name table for these types of diagnostics and they use the template "change_over_time_in_<prognostic>[_due_to_<process>]", e.g.  change_over_time_in_atmosphere_mass_content_of_water_due_to_advection.

Therefore the changes here convert diagnostics with existing mappings of "tendency_of_" names to "change_over_time_in_" names. There are a more of these mappings with diagnostics I am less aware of that may also benefit from these changes.

**Comment by pdearnshaw** [comment]
Copy of text in the uploaded file:

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s05i181|change_over_time_in_air_temperature_due_to_convection|K|y|
|m01s05i182|change_over_time_in_specific_humidity_due_to_convection|kg kg-1|y|
|m01s05i185|change_over_time_in_eastward_wind_due_to_convection|m s-1|y|
|m01s05i186|change_over_time_in_northward_wind_due_to_convection|m s-1|y|
|m01s06i185|change_over_time_in_eastward_wind_due_to_gravity_wave_drag|m s-1|y|
|m01s06i186|change_over_time_in_northward_wind_due_to_gravity_wave_drag|m s-1|y|
|m01s12i181|change_over_time_in_air_temperature_due_to_advection|K|y|
|m01s12i182|change_over_time_in_specific_humidity_due_to_advection|kg kg-1|y|
|m01s12i183|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_advection|kg kg-1|y|
|m01s12i184|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_advection|kg kg-1|y|
|m01s12i185|change_over_time_in_eastward_wind_due_to_advection|m s-1|y|
|m01s12i186|change_over_time_in_northward_wind_due_to_advection|m s-1|y|
|m01s13i181|change_over_time_in_air_temperature_due_to_diffusion|K|y|
|m01s13i182|change_over_time_in_specific_humidity_due_to_diffusion|kg kg-1|y|
|m01s13i185|change_over_time_in_eastward_wind_due_to_diffusion|m s-1|y|
|m01s13i186|change_over_time_in_northward_wind_due_to_diffusion|m s-1|y|
|m01s30i181|change_over_time_in_air_temperature|K|y|
|m01s30i182|change_over_time_in_specific_humidity|kg kg-1|y|
|m01s30i183|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air|kg kg-1|y|
|m01s30i184|change_over_time_in_mass_fraction_of_cloud_ice_in_air|kg kg-1|y|
|m01s30i185|change_over_time_in_eastward_wind|m s-1|y|
|m01s30i186|change_over_time_in_northward_wind|m s-1|y|
|m01s30i187|change_over_time_in_upward_air_velocity|m s-1|y|

**Comment by marqh** [comment]
hello @pdearnshaw 

as with #83 I think 

 * `eastward_` => `x_`
 * `northward_` => `y_`

would be a helpful change

**Comment by pdearnshaw** [comment]
Updated branch with

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s05i181|change_over_time_in_air_temperature_due_to_convection|K|y|
|m01s05i182|change_over_time_in_specific_humidity_due_to_convection|kg kg-1|y|
|m01s05i185|change_over_time_in_x_wind_due_to_convection|m s-1|y|
|m01s05i186|change_over_time_in_y_wind_due_to_convection|m s-1|y|
|m01s06i185|change_over_time_in_x_wind_due_to_gravity_wave_drag|m s-1|y|
|m01s06i186|change_over_time_in_y_wind_due_to_gravity_wave_drag|m s-1|y|
|m01s12i181|change_over_time_in_air_temperature_due_to_advection|K|y|
|m01s12i182|change_over_time_in_specific_humidity_due_to_advection|kg kg-1|y|
|m01s12i183|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_advection|kg kg-1|y|
|m01s12i184|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_advection|kg kg-1|y|
|m01s12i185|change_over_time_in_x_wind_due_to_advection|m s-1|y|
|m01s12i186|change_over_time_in_y_wind_due_to_advection|m s-1|y|
|m01s13i181|change_over_time_in_air_temperature_due_to_diffusion|K|y|
|m01s13i182|change_over_time_in_specific_humidity_due_to_diffusion|kg kg-1|y|
|m01s13i185|change_over_time_in_x_wind_due_to_diffusion|m s-1|y|
|m01s13i186|change_over_time_in_y_wind_due_to_diffusion|m s-1|y|
|m01s30i181|change_over_time_in_air_temperature|K|y|
|m01s30i182|change_over_time_in_specific_humidity|kg kg-1|y|
|m01s30i183|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air|kg kg-1|y|
|m01s30i184|change_over_time_in_mass_fraction_of_cloud_ice_in_air|kg kg-1|y|
|m01s30i185|change_over_time_in_x_wind|m s-1|y|
|m01s30i186|change_over_time_in_y_wind|m s-1|y|
|m01s30i187|change_over_time_in_upward_air_velocity|m s-1|y|

**Comment by marqh** [comment]
merged, with thanks
