### ISSUE TITLE
STASH Code to CF name translations: Adding new standard name mappings

### ISSUE THREAD

**Issue by pdearnshaw** [metarelate/metOcean#85]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pdearnshaw
https://www.metarelate.net/metOcean/controlpanel/?branch=0671380afe21b4fa1b3482f40debd808ff8a5f78%2F

**Comment by pdearnshaw** [comment]
Copy of uploaded text file:

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s00i272|mass_fraction_of_rain_in_air|kg kg-1|n|
|m01s00i273|mass_fraction_of_graupel_in_air|kg kg-1|n|
|m01s00i388|virtual_potential_temperature|K|n|
|m01s00i389|air_density|kg m-3|n|
|m01s00i391|humidity_mixing_ratio|kg kg-1|n|
|m01s00i392|cloud_liquid_water_mixing_ratio|kg kg-1|n|
|m01s00i393|cloud_ice_mixing_ratio|kg kg-1|n|
|m01s00i394|rain_mixing_ratio|kg kg-1|n|
|m01s00i395|graupel_mixing_ratio|kg kg-1|n|
|m01s03i216|upward_heat_flux_in_air|W m-2|n|
|m01s03i222|upward_water_vapor_flux_in_air|kg m-2 s-1|n|
|m01s03i339|bulk_richardson_number|1|n|
|m01s03i380|surface_net_downward_radiative_flux|W m-2|n|
|m01s03i390|wind_speed_shear|m s-1|n|
|m01s03i538|surface_drag_coefficient_for_momentum_in_air|1|n|
|m01s03i541|surface_drag_coefficient_for_heat_in_air|1|n|

**Comment by marqh** [comment]
merged, with thanks
