### ISSUE TITLE
STASH Code to CF name translations: Adding new standard name mappings for diagnostic increments (more controversial)

### ISSUE THREAD

**Issue by pdearnshaw** [metarelate/metOcean#87]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pdearnshaw
https://www.metarelate.net/metOcean/controlpanel/?branch=cf1ff0d1f017a20fc9f8ecd843062c86bd183063%2F

**Comment by pdearnshaw** [comment]
These diagnostics have standard names using processes that have not been used in any previous standard name. Some of them are UM specific, but cannot think of anything more suitable at present.

Copy of uploaded text file:

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s04i141|change_over_time_in_air_temperature_due_to_pc2_checks|K|n|
|m01s04i142|change_over_time_in_specific_humidity_due_to_pc2_checks|kg kg-1|n|
|m01s04i143|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_pc2_checks|kg kg-1|n|
|m01s04i144|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_pc2_checks|kg kg-1|n|
|m01s04i152|change_over_time_in_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_checks|1|n|
|m01s04i153|change_over_time_in_liquid_water_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_checks|1|n|
|m01s04i154|change_over_time_in_ice_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_checks|1|n|
|m01s10i181|change_over_time_in_air_temperature_due_to_pressure_solver|K|n|
|m01s10i185|change_over_time_in_eastward_wind_due_to_pressure_solver|m s-1|n|
|m01s10i186|change_over_time_in_northward_wind_due_to_pressure_solver|m s-1|n|
|m01s10i187|change_over_time_in_upward_air_velocity_due_to_pressure_solver|m s-1|n|
|m01s12i381|change_over_time_in_air_temperature_due_to_adv_correction|K|n|
|m01s12i382|change_over_time_in_specific_humidity_due_to_adv_correction|kg kg-1|n|
|m01s12i383|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_adv_correction|kg kg-1|n|
|m01s12i384|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_adv_correction|kg kg-1|n|
|m01s12i389|change_over_time_in_mass_fraction_of_rain_in_air_due_to_adv_correction|kg kg-1|n|
|m01s12i391|change_over_time_in_mass_fraction_of_graupel_in_air_due_to_adv_correction|kg kg-1|n|
|m01s12i395|change_over_time_in_humidity_mixing_ratio_due_to_adv_correction|kg kg-1|n|
|m01s12i396|change_over_time_in_cloud_liquid_water_mixing_ratio_due_to_adv_correction|kg kg-1|n|
|m01s12i397|change_over_time_in_cloud_ice_mixing_ratio_due_to_adv_correction|kg kg-1|n|
|m01s12i398|change_over_time_in_rain_mixing_ratio_due_to_adv_correction|kg kg-1|n|
|m01s12i399|change_over_time_in_graupel_mixing_ratio_due_to_adv_correction|kg kg-1|n|
|m01s14i181|change_over_time_in_air_temperature_due_to_energy_correction|K|n|
|m01s16i161|change_over_time_in_air_temperature_due_to_pc2_initialisation|K|n|
|m01s16i162|change_over_time_in_specific_humidity_due_to_pc2_initialisation|kg kg-1|n|
|m01s16i163|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_pc2_initialisation|kg kg-1|n|
|m01s16i164|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_pc2_initialisation|kg kg-1|n|
|m01s16i172|change_over_time_in_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_initialisation|1|n|
|m01s16i173|change_over_time_in_liquid_water_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_initialisation|1|n|
|m01s16i174|change_over_time_in_ice_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_initialisation|1|n|
|m01s16i181|change_over_time_in_air_temperature_due_to_pc2_pressure_change|K|n|
|m01s16i182|change_over_time_in_specific_humidity_due_to_pc2_pressure_change|kg kg-1|n|
|m01s16i183|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_pc2_pressure_change|kg kg-1|n|
|m01s16i184|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_pc2_pressure_change|kg kg-1|n|
|m01s16i192|change_over_time_in_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_pressure_change|1|n|
|m01s16i193|change_over_time_in_liquid_water_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_pressure_change|1|n|
|m01s16i194|change_over_time_in_ice_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_pressure_change|1|n|
|m01s35i003|change_over_time_in_eastward_wind_due_to_stochastic_kinetic_energy_backscatter|m s-1|n|
|m01s35i004|change_over_time_in_northward_wind_due_to_stochastic_kinetic_energy_backscatter|m s-1|n|
|m01s35i024|change_over_time_in_air_potential_temperature_due_to_stochastic_perturbation_of_tendencies|K|n|
|m01s35i025|change_over_time_in_specific_humidity_due_to_stochastic_perturbation_of_tendencies|kg kg-1|n|
|m01s35i026|change_over_time_in_eastward_wind_due_to_stochastic_perturbation_of_tendencies|m s-1|n|
|m01s35i027|change_over_time_in_northward_wind_due_to_stochastic_perturbation_of_tendencies|m s-1|n|
|m01s35i029|change_over_time_in_air_temperature_due_to_stochastic_perturbation_of_tendencies|K|n|

**Comment by marqh** [comment]
hello @pdearnshaw 

as with #83 I think 

 * `eastward_` => `x_`
 * `northward_` => `y_`

would be a helpful change

**Comment by pdearnshaw** [comment]
Have updated branch with

|STASH(msi)|CFName|units|force_update(y/n)|
|m01s04i141|change_over_time_in_air_temperature_due_to_pc2_checks|K|n|
|m01s04i142|change_over_time_in_specific_humidity_due_to_pc2_checks|kg kg-1|n|
|m01s04i143|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_pc2_checks|kg kg-1|n|
|m01s04i144|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_pc2_checks|kg kg-1|n|
|m01s04i152|change_over_time_in_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_checks|1|n|
|m01s04i153|change_over_time_in_liquid_water_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_checks|1|n|
|m01s04i154|change_over_time_in_ice_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_checks|1|n|
|m01s10i181|change_over_time_in_air_temperature_due_to_pressure_solver|K|n|
|m01s10i185|change_over_time_in_x_wind_due_to_pressure_solver|m s-1|y|
|m01s10i186|change_over_time_in_y_wind_due_to_pressure_solver|m s-1|y|
|m01s10i187|change_over_time_in_upward_air_velocity_due_to_pressure_solver|m s-1|n|
|m01s12i381|change_over_time_in_air_temperature_due_to_advection_corrections|K|y|
|m01s12i382|change_over_time_in_specific_humidity_due_to_advection_corrections|kg kg-1|y|
|m01s12i383|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_advection_corrections|kg kg-1|y|
|m01s12i384|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_advection_corrections|kg kg-1|y|
|m01s12i389|change_over_time_in_mass_fraction_of_rain_in_air_due_to_advection_corrections|kg kg-1|y|
|m01s12i391|change_over_time_in_mass_fraction_of_graupel_in_air_due_to_advection_corrections|kg kg-1|y|
|m01s12i395|change_over_time_in_humidity_mixing_ratio_due_to_advection_corrections|kg kg-1|y|
|m01s12i396|change_over_time_in_cloud_liquid_water_mixing_ratio_due_to_advection_corrections|kg kg-1|y|
|m01s12i397|change_over_time_in_cloud_ice_mixing_ratio_due_to_advection_corrections|kg kg-1|y|
|m01s12i398|change_over_time_in_rain_mixing_ratio_due_to_advection_corrections|kg kg-1|y|
|m01s12i399|change_over_time_in_graupel_mixing_ratio_due_to_advection_corrections|kg kg-1|y|
|m01s14i181|change_over_time_in_air_temperature_due_to_energy_correction|K|n|
|m01s16i161|change_over_time_in_air_temperature_due_to_pc2_initialisation|K|n|
|m01s16i162|change_over_time_in_specific_humidity_due_to_pc2_initialisation|kg kg-1|n|
|m01s16i163|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_pc2_initialisation|kg kg-1|n|
|m01s16i164|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_pc2_initialisation|kg kg-1|n|
|m01s16i172|change_over_time_in_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_initialisation|1|n|
|m01s16i173|change_over_time_in_liquid_water_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_initialisation|1|n|
|m01s16i174|change_over_time_in_ice_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_initialisation|1|n|
|m01s16i181|change_over_time_in_air_temperature_due_to_pc2_pressure_change|K|n|
|m01s16i182|change_over_time_in_specific_humidity_due_to_pc2_pressure_change|kg kg-1|n|
|m01s16i183|change_over_time_in_mass_fraction_of_cloud_liquid_water_in_air_due_to_pc2_pressure_change|kg kg-1|n|
|m01s16i184|change_over_time_in_mass_fraction_of_cloud_ice_in_air_due_to_pc2_pressure_change|kg kg-1|n|
|m01s16i192|change_over_time_in_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_pressure_change|1|n|
|m01s16i193|change_over_time_in_liquid_water_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_pressure_change|1|n|
|m01s16i194|change_over_time_in_ice_cloud_volume_fraction_in_atmosphere_layer_due_to_pc2_pressure_change|1|n|
|m01s35i003|change_over_time_in_x_wind_due_to_stochastic_kinetic_energy_backscatter|m s-1|y|
|m01s35i004|change_over_time_in_y_wind_due_to_stochastic_kinetic_energy_backscatter|m s-1|y|
|m01s35i024|change_over_time_in_air_potential_temperature_due_to_stochastic_perturbation_of_tendencies|K|n|
|m01s35i025|change_over_time_in_specific_humidity_due_to_stochastic_perturbation_of_tendencies|kg kg-1|n|
|m01s35i026|change_over_time_in_x_wind_due_to_stochastic_perturbation_of_tendencies|m s-1|y|
|m01s35i027|change_over_time_in_y_wind_due_to_stochastic_perturbation_of_tendencies|m s-1|y|
|m01s35i029|change_over_time_in_air_temperature_due_to_stochastic_perturbation_of_tendencies|K|n|

**Comment by marqh** [comment]
merged, with thanks
