### ISSUE TITLE
restore 3245

### ISSUE THREAD

**Issue by marqh** [metarelate/metOcean#89]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pdearnshaw
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=b6c6ed36770484219a5f88069815abf88ecb620c%2F

**Comment by marqh** [comment]
i think this overwrite was a mistake on 2 grounds
1. the unit for relative humidity should be %
1. this translation was constrained to a height of 1.5m

https://www.metarelate.net/metOcean/mapping/67f8eb5c08d66657811ebeeee7518667cac48cde/?branch=b6c6ed36770484219a5f88069815abf88ecb620c/

**Comment by pdearnshaw** [comment]
Looks fine to me.
