### ISSUE TITLE
restore humidity mass fraction

### ISSUE THREAD

**Issue by marqh** [metarelate/metOcean#90]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pdearnshaw
@scwhitehouse
@ehogan
@marqh
https://www.metarelate.net/metOcean/controlpanel/?branch=21d312748972bc5ccc36b4624ccb4c9592edea5f%2F

**Comment by marqh** [comment]
```
|STASH(msi)|CFName|units|force_update(y/n)|
|m01s08i229|mass_fraction_of_unfrozen_water_in_soil_moisture|kg kg-1|y|
|m01s08i230|mass_fraction_of_frozen_water_in_soil_moisture|kg kg-1|y|
|m01s16i204|relative_humidity|%|y|
|m01s16i256|relative_humidity|%|y|
|m01s30i113|relative_humidity|%|y|

```

**Comment by pdearnshaw** [comment]
This all looks fine to me. My mistake in believing Relative Humidity was a fraction, not a percent!
