### ISSUE TITLE
Additional grib phenomenon translations for WAFC codes

### ISSUE THREAD

**Issue by pp-mo** [metarelate/metOcean#93]
(? think WAFC = "World Area Forecast Center" ?)

I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.
Notify:
@pp-mo
https://www.metarelate.net/metOcean/controlpanel/?branch=cd381ce8448872f1a5d06a36e973318af0c94d4e%2F

**Comment by marqh** [comment]
these new translations all look good, 
adopted and merged, thank you
