### ISSUE TITLE
CF to GRIB2 mass_fraction_of_cloud_liquid_water_in_air and mass_fraction_of_cloud_ice_in_air

### ISSUE THREAD

**Issue by BHFock** [metarelate/metOcean#95]
I propose these changes to Metarelate's metOcean knowledge base.
The changes are correct, to the best of my knowledge.
I agree to my username being used to label these changes.

http://www.metarelate.net/metOcean/controlpanel/?branch=c69de422800c062dff1d2b58172e0649c6ab7c28

http://www.metarelate.net/metOcean/list_mappings/True/?ref=%22c69de422800c062dff1d2b58172e0649c6ab7c28%2F%22

The added mappings are:

- mass_fraction_of_cloud_liquid_water_in_air to "specific cloud liquid water content", http://codes.wmo.int/grib2/codeflag/4.2/_0-1-83
 
- Map mass_fraction_of_cloud_ice_in_air to "specific cloud ice water content", http://codes.wmo.int/grib2/codeflag/4.2/_0-1-84|

These changes have been discussed here: https://github.com/SciTools/iris-grib/pull/160

**Comment by marqh** [comment]
thank you @BHFock 

this is well defined and expressed.  I have merged the content and pushed the change request to iris grib to be merged there too

marqh
